Use trigger service
digital-asset/ex-healthcare-claims-processing pull request #119
Opened 2021-05-13 15:31 UTC by richardkapolnai-da

2021-05-13 22:48 UTC, tamaskalcza-da requested changes

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +        raise RuntimeError(result.stderr)
```suggestion
    result = subprocess.run(['daml', 'damlc', 'inspect-dar', '--json', dar], capture_output=True, check=True)
```

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +    return inspect["main_package_id"]
Minor, feel free to ignore.
```suggestion
    dar_properties = json.loads(result.stdout)
    return dar_properties["main_package_id"]
```

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +         "--wall-clock-time", "--dar", dar, ])
```suggestion
         "--wall-clock-time", "--dar", dar])
```

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +        logger.warning(f'Could not found subprocess to kill')
Isn't this what you meant?
```suggestion
        logger.warning(f'Could not found process {process.pid} to kill')
```
Or remove don't use `f` interpolation.

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +def kill_background_process(process):
I guess this method works for any process, not just background ones. If so, I'd simply name it to `kill_process`.

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/startTriggers.py
> +    time.sleep(3)
?

2021-05-13 22:48 UTC, tamaskalcza-da commented on scripts/startTriggers.py
> +triggers_with_parties = [
Minor, but why list and not a dictionary?

2021-05-13 22:48 UTC, tamaskalcza-da commented on src/test/java/com/daml/product/healthcareclaims/HealthcareClaimsProcessingIT.java
> +    logger.debug("starting triggers");
I'd drop the logger, don't see the benefit here.

2021-05-14 07:29 UTC, richardkapolnai-da commented on scripts/damlassistant.py
> +    logger.info(f"Starting {package_id}:{trigger} as {party}")
May I ask what's the reason? I find the interpolated string slightly more readable.

2021-05-14 07:35 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +triggers_with_parties = [
Because neither of the fields are proper keys (a party may have multiple triggers and vice versa)

2021-05-14 07:36 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +    time.sleep(3)
ooops, good catch, no idea, removing :thinking:

2021-05-14 07:41 UTC, richardkapolnai-da commented on scripts/damlassistant.py
> +logger = logging.getLogger(__name__)
done

2021-05-14 07:44 UTC, richardkapolnai-da commented on scripts/damlassistant.py
> +    url = f'http://localhost:{DEFAULT_TRIGGER_SERVICE_PORT}/v1/triggers'
On a second thought: I don't need them anywhere else, and there is no nice way prevent exporting if I make them global. What do you think?

2021-05-14 07:45 UTC, richardkapolnai-da commented on scripts/damlassistant.py
> +def kill_background_process(process):
done

2021-05-14 07:48 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +    time.sleep(3)
I know: it's for waiting the triggers to start, keeping for now, but renaming to be self-explanatory.
Without this, the message below is basically lost between TriggerService log messages

2021-05-14 07:55 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +    time.sleep(3)
Refactored a bit.

2021-05-14 07:57 UTC, richardkapolnai-da commented on src/test/java/com/daml/product/healthcareclaims/HealthcareClaimsProcessingIT.java
> +    logger.debug("starting triggers");
done

2021-05-14 08:00 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +    logger.info(f"Starting {package_id}:{trigger} as {party}")
Performance. If you do an interpolation, that is always evaluated. If you use the argument-passing version, you have a constant string value, and the logging framework will use the arguments in a lazy fashion. For instance if it does not have to log because of the current log level.

Again: this is minor and a bit theoretical at this point, this is not a mission critical system. :)

2021-05-14 08:01 UTC, tamaskalcza-da commented on scripts/damlassistant.py
> +    url = f'http://localhost:{DEFAULT_TRIGGER_SERVICE_PORT}/v1/triggers'
I'll leave it up to you.

2021-05-14 08:07 UTC, tamaskalcza-da commented on scripts/startTriggers.py
> +triggers_with_parties = [
In this case I especially prefer dictionary, like so:
```python
triggers_with_parties = {
    "Patient1": [
        "Triggers.AcknowledgeAndDiscloseTrigger:acknowledgeAndDiscloseTrigger",
        "Triggers.AcceptPatientPaymentRequestTrigger:acceptPatientPaymentRequestTrigger"
    ]
}
```

But again: I'll leave it up to your judgement. :)

2021-05-14 08:23 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +triggers_with_parties = [
Could be, but iterating over this is slightly easier this way, so (`for party, triggerName in triggers_with_parties`), so I'd appreciate letting me keep this structure. :) I don't have a strong preference though.
(Another: this structure may be easier to understand for any random user.)

2021-05-14 08:24 UTC, richardkapolnai-da commented on scripts/startTriggers.py
> +sandbox_port = sys.argv[1]
done

2021-05-14 08:25 UTC, richardkapolnai-da commented on scripts/damlassistant.py
> +    logger.info(f"Starting {package_id}:{trigger} as {party}")
Agreed, let's keep this, my argument: in this case, readability is more valuable than memory/cpu usage.

2021-05-14 08:40 UTC, tamaskalcza-da approved these changes

2021-05-14 08:42 UTC, merged